import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header";
import { SidebarProvider } from "@/shared/ui/sidebar";
import AppSidebar from "@/widgets/sidebar/app-sidebar";
import { QueryProvider } from "@/shared/api/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ru"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <SidebarProvider>
            <div className="flex w-full">
              <AppSidebar />
              <div className="flex flex-1 flex-col">
                <Header />
                <main className="flex flex-1 min-h-screen flex-col items-center justify-between p-24 font-sans">
                  {children}
                </main>
              </div>
            </div>
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
